name: Auto Build Scanner
on:
  create:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: 'gradle'

      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            app/build
            buildSrc/build
            mi_sdk/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK with Gradle (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
          NAME_SUFFIX: '.dev'
        run: |
          chmod +x gradlew
          ./gradlew build


      - name: Build APK with Gradle (MAIN)
        if: ${{ github.ref != 'refs/heads/dev' }}
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew build
        env:
          NAME_SUFFIX: ''

      - name: Upload Released APK armv8
        uses: actions/upload-artifact@v3
        with:
          name: scanner-armv8
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload Released APK x86
        uses: actions/upload-artifact@v3
        with:
          name: scanner-x86 (Emulator)
          path: app/build/outputs/apk/release/app-x86-release.apk

      - name: Upload Released Universal APK
        uses: actions/upload-artifact@v3
        with:
          name: scanner-universal
          path: app/build/outputs/apk/release/app-universal-release.apk

      - name: Upload APKs to Release Page
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            app/build/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/outputs/apk/release/app-x86-release.apk
            app/build/outputs/apk/release/app-universal-release.apk
